name: Artifact Transfer Demo

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build output data" > build.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-build
          path: build.txt

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: my-build

      - name: Show file
        run: cat build.txt
